name: ci
on: [ push ]
jobs:
  common:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

#      - name: Get pnpm store directory
#        shell: bash
#        run: |
#          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV



      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ~/.pnpm-store

  build:
    runs-on: ubuntu-latest
    name: build
    needs: common
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: ~/.pnpm-store
      - name: Display structure of downloaded files
        run: ls -R

#      - name: Restore pnpm cache
#        uses: actions/cache@v3
#        with:
#          path: ~/.pnpm-store
#          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: build
        run: pnpm run build

#  test:
#    runs-on: ubuntu-latest
#    name: test
#    needs: common
#    steps:
#      - name: test
#        run: pnpm run test
#
#  size_limit:
#    runs-on: ubuntu-latest
#    name: size limit
#    needs: common
#    steps:
#      - name: size limit
#        run: pnpm run size-limit
