name: ci
on: [ push ]
jobs:
  common:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

  build:
    runs-on: ubuntu-latest
    name: build
    needs: common
    steps:
      - name: build
        run: pnpm run build

  test:
    runs-on: ubuntu-latest
    name: test
    needs: common
    steps:
      - name: test
        run: pnpm run test

  size_limit:
    runs-on: ubuntu-latest
    name: size limit
    needs: common
    steps:
      - name: size limit
        run: pnpm run size-limit
