name: ci
on: [push]
jobs:
  common:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

  build:
    name: Build
    needs: common
    steps:
      - name: Build
        run: pnpm run build

  test:
    name: Test
    needs: common
    steps:
      - name: Test
        run: pnpm run test

  size_limit:
    name: Size limit
    needs: common
    steps:
      - name: Size limit
        run: pnpm run size-limit
